name: Nekogram-Lite

on: workflow_dispatch
jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: setup keystore
        run: |
          echo $SIGNING_KEY | base64 -di > TMessagesProj/config/release.keystore
        env:
          SIGNING_KEY: ${{ secrets.ANDROID_KEYSTORE }}
      - name: Build
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          ALIAS_NAME: ${{ secrets.ALIAS_NAME }}
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
        run: |
          ./gradlew assembleRelease
      - name: Upload to channel
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          OUTPUT="TMessagesProj/build/outputs"
          find $OUTPUT/apk -name "*.apk" -print0 | while read -d $'\0' name
          do
              curl https://api.telegram.org/bot${BOT_TOKEN}/sendDocument -X POST -F chat_id="$CHANNEL_ID" -F document="@$name"
          done
      - uses: actions/upload-artifact@master
        name: Upload artifact
        with:
          name: Nekogram-Lite
          path: TMessagesProj/build/outputs/
